namespace Crossout.Data.Stats.Main
{
    // *** Generator: v0.4 This class is automatically generated, please use the non generated variant of this class ***
    public partial class PartStatsWeapon : PartStatsBase
    {
        public PartStatsWeapon(string key) : base(key) { }
        public bool ods_export {get;set;}
        public string inherit {get;set;}
        public bool released {get;set;}
        public bool tradeable {get;set;}
        public string item_type {get;set;}
        public string model {get;set;}
        public string subtype {get;set;}
        public string editor_type {get;set;}
        public string taglist {get;set;}
        public string ui_part_type_icon {get;set;}
        public string ui_part_filter {get;set;}
        public string ui_part_series {get;set;}
        public string ui_part_type {get;set;}
        public string ui_hud_icon {get;set;}
        public double health {get;set;}
        public bool damageable {get;set;}
        public int rarity {get;set;}
        public double physics_mass {get;set;}
        public string physics_material {get;set;}
        public int power_require {get;set;}
        public string @class {get;set;}
        public int fire_rate {get;set;}
        public double damage {get;set;}
        public double hit_impulse {get;set;}
        public int rot_speed {get;set;}
        public double optimal_range {get;set;}
        public double max_range {get;set;}
        public double ai_optimal_dist {get;set;}
        public double spread_stat {get;set;}
        public double spread_stat_max {get;set;}
        public double spread_move {get;set;}
        public double spread_move_max {get;set;}
        public double spread_inc {get;set;}
        public double spread_dec {get;set;}
        public double spread_rot_inc {get;set;}
        public string projectile {get;set;}
        public int max_pitch {get;set;}
        public int min_pitch {get;set;}
        public double damage_rating {get;set;}
        public double fire_rate_rating {get;set;}
        public double range_rating {get;set;}
        public double accuracy_rating {get;set;}
        public double overheat_rating {get;set;}
        public int universal_rating {get;set;}
        public bool important {get;set;}
        public int heat_max {get;set;}
        public double heat_inc {get;set;}
        public double heat_dec {get;set;}
        public string damage_perk {get;set;}
        public int require_faction_level {get;set;}
        public bool salvageable {get;set;}
        public int salvage_Scrap_Common {get;set;}
        public int salvage_Scrap_Rare {get;set;}
        public int salvage_Scrap_Epic {get;set;}
        public string fusion {get;set;}
        public string fusion_cost {get;set;}
        public string perk {get;set;}
        public string require_faction {get;set;}
        public double recoil_impulse {get;set;}
        public double speedup_time {get;set;}
        public double slowdown_time {get;set;}
        public int max_yaw {get;set;}
        public int min_yaw {get;set;}
        public string xopedia_keyword {get;set;}
        public string ui_aim_type {get;set;}
        public int ammo {get;set;}
        public int projectile_speed {get;set;}
        public double projectile_damping {get;set;}
        public double blast_damage {get;set;}
        public int blast_damage_experimental {get;set;}
        public int blast_impulse {get;set;}
        public double blast_radius {get;set;}
        public int blast_radius_experimental {get;set;}
        public bool sniper_weapon {get;set;}
        public int pellet_count {get;set;}
        public double damage_transmission {get;set;}
        public int collision_resist {get;set;}
        public int collision_damage {get;set;}
        public double spread_scale_x {get;set;}
        public double spread_scale_y {get;set;}
        public bool secondary_weapon {get;set;}
        public double shooting_cooldown {get;set;}
        public string ui_perks_1_ {get;set;}
        public bool conical_explosion {get;set;}
        public bool editor_horizontal_rotation {get;set;}
        public double projectile_detonation_radius {get;set;}
        public int projectile_launch_angle {get;set;}
        public double projectile_ttl {get;set;}
        public int burst_size {get;set;}
        public int projectile_rot_radius {get;set;}
        public bool fixed_barrel {get;set;}
        public int lock_angle {get;set;}
        public bool check_restriction_overlap {get;set;}
        public string damage_type_direct {get;set;}
        public int death_blast_damage {get;set;}
        public int death_blast_damage_experimental {get;set;}
        public double death_blast_radius {get;set;}
        public int death_blast_radius_experimental {get;set;}
        public double charging_time {get;set;}
        public bool big_explosion {get;set;}
        public bool ai_ignore_pitch {get;set;}
        public int projectile_slowdown_pitch {get;set;}
        public double projectile_slowdown_pitch_coef {get;set;}
        public int gravity_multiplyer {get;set;}
        public int car_camera_correction_y {get;set;}
        public string target_area_effect {get;set;}
        public double pitch_coef {get;set;}
        public int zero_pitch {get;set;}
        public int heavy_unique_count {get;set;}
        public int dodge_angular_acceleration {get;set;}
        public int projectile_phase2_time {get;set;}
        public bool innate_ai {get;set;}
        public bool lock_target {get;set;}
        public bool charging_need_hold {get;set;}
        public string damage_type_blast {get;set;}
        public string spell {get;set;}
        public double score_damage_coef {get;set;}
        public int calcination_inc {get;set;}
        public bool fire_without_target {get;set;}
        public double barrel_detonation_radius {get;set;}
        public int projectile_angular_speed {get;set;}
        public int turret_work_time {get;set;}
        public int self_calcination_inc {get;set;}
        public int cylinder_radius {get;set;}
        public int area_speed {get;set;}
        public int slow_fire_rate {get;set;}
    }
}
