namespace Crossout.Data.Stats.Main
{
    // *** Generator: v0.4 This class is automatically generated, please use the non generated variant of this class ***
    public partial class PartStatsCore : PartStatsBase
    {
        public PartStatsCore(string key) : base(key) { }
        public bool ods_export {get;set;}
        public string inherit {get;set;}
        public string @class {get;set;}
        public bool released {get;set;}
        public bool tradeable {get;set;}
        public string xopedia_keyword {get;set;}
        public string item_type {get;set;}
        public string model {get;set;}
        public string subtype {get;set;}
        public string editor_type {get;set;}
        public string ui_part_filter {get;set;}
        public string taglist {get;set;}
        public string ui_part_type_icon {get;set;}
        public string ui_part_type {get;set;}
        public int health {get;set;}
        public int rarity {get;set;}
        public string physics_material {get;set;}
        public int physics_mass {get;set;}
        public int require_faction_level {get;set;}
        public double engine_power_mul {get;set;}
        public double engine_max_speed_mul {get;set;}
        public int critical_mass_add {get;set;}
        public bool engine_unique {get;set;}
        public int universal_rating {get;set;}
        public bool important {get;set;}
        public string fusion {get;set;}
        public string fusion_cost {get;set;}
        public bool salvageable {get;set;}
        public int salvage_Scrap_Common {get;set;}
        public int salvage_Scrap_Rare {get;set;}
        public int salvage_Scrap_Epic {get;set;}
        public int power_require {get;set;}
        public int tonnage_add {get;set;}
        public string require_faction {get;set;}
        public string ui_perks_1_ {get;set;}
        public double shooting_cooldown_mul {get;set;}
        public double skill_cooldown_mul {get;set;}
        public string perk {get;set;}
        public int power {get;set;}
        public bool generator_unique {get;set;}
        public int death_blast_damage {get;set;}
        public int death_blast_radius {get;set;}
        public double ammo_mul {get;set;}
        public int direct_resist {get;set;}
        public int blast_resist {get;set;}
        public int gasoline_harvest {get;set;}
        public string item_reward {get;set;}
        public double heat_inc_mul {get;set;}
        public double heat_inc_high_speed {get;set;}
        public double heat_dec_mul {get;set;}
        public double heat_dec_low_speed {get;set;}
        public int radar_radius {get;set;}
        public int infravision_radius {get;set;}
        public int radio_radius {get;set;}
        public string ui_hud_icon {get;set;}
        public int skill_unique_count {get;set;}
        public int work_time {get;set;}
        public int cooldown {get;set;}
        public bool editor_horizontal_rotation {get;set;}
        public int deploy_ammo {get;set;}
        public int firing_delay {get;set;}
        public string deploy_def {get;set;}
        public string pre_deploy_model {get;set;}
        public int ai_optimal_dist {get;set;}
        public int heat_max {get;set;}
        public double heat_inc {get;set;}
        public double heat_dec {get;set;}
        public bool activate_hold {get;set;}
        public int booster_ammo {get;set;}
        public int fire_rate {get;set;}
        public int boost_value {get;set;}
        public string ui_aim_type {get;set;}
        public bool highlighting {get;set;}
        public int fov_value_max {get;set;}
        public int fov_value_min {get;set;}
        public int fov_value_step {get;set;}
        public bool is_autolifting_allowed {get;set;}
        public int behavior_evade_radius {get;set;}
        public string deploy_design {get;set;}
        public string behavior {get;set;}
        public double deploy_ammo_mul {get;set;}
        public string remap_texture {get;set;}
        public string platform_exclusive {get;set;}
        public double booster_ammo_mul {get;set;}
        public int jammer_radius {get;set;}
        public string spell {get;set;}
        public double shooting_cooldown_mul_high_speed {get;set;}
    }
}
